default:
	gcc -o p1 p1.c -lpthread -g -Wall
	gcc -o p2 p2.c -lpthread -Wall
	gcc -o p3 p3.c -lpthread -lrt -Wall
	gcc -o p4 p4.c -lpthread -Wall
	gcc -o p5 p5.c -lpthread -lm -Wall
	gcc -o p6 p6.c -lpthread -lm -Wall

clean:
	rm -rf p1 p2 p3 p4 p5 p6