build:
	gcc example.c -o example -lpthread
	gcc example_1.c -o example_1 -lpthread
	gcc example_2.c -o example_2 -lpthread
	gcc example_3.c -o example_3 -lpthread
	gcc example_4.c -o example_4 -lpthread
	gcc add_serial.c -o add_serial -lpthread
	gcc add_serial_5.c -o add_serial_5 -lpthread
	
clean:
	rm example add_serial example_4 example_3 example_2 example_1 add_serial_5